import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "The Wok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#000000] relative">
        <Navbar />
          {children}
        </body>
    </html>
  );
}
